audio:
  analysis_interval: 0.1
  frame_length: 2048
  hop_length: 512
  sample_rate: 22050
logging:
  level: INFO
output:
  audio_features_dir: audio_features
  base_dir: video_analyzer
  hdf5_dir: hdf5_data
