# 긴 영상 재미 클립 추출 시스템 설정
system:
  name: "재밌는 클립 추출 시스템"
  version: "1.0.0"
  
# 1단계: 하이라이트 클러스터링
clustering:
  eps: 12                    # DBSCAN 거리 임계값 (초)
  min_samples: 1            # 최소 샘플 수
  expansion_buffer: 3       # 단일 클러스터 확장 버퍼 (초)

# 2단계: 윈도우 생성 및 점수 계산  
window_generation:
  length_range: {min: 18, max: 40, step: 1}   # 윈도우 길이들 (초)
  step_size: 1                      # 슬라이딩 간격 (초)
  position_ratio: 0.75              # 하이라이트 위치 비율 (3/4 지점)
  full_grid_search: true           # 전체 그리드 서치 모드 (기본값: false)
  grid_step: 1.0                    # 그리드 서치 간격 (초)

  
# 3단계: XGBoost 모델
model:
  path: "models/xgb_funclip_extracter/xgb_fun_classifier.pkl"
  device: "cpu"                     # XGBoost는 CPU 사용
  
# 4단계: NMS 로직 - 클립 선별 (기본값, select_clips.py에서 오버라이드)
selection:
  iou_threshold: 0.3               # NMS IoU 임계값 (0~1) 0이면 약간이라도 겹치는 클립은 버려짐
  target_clips: 10                  # 추출할 클립 개수
  min_score: 0.5                   # 최소 재미도 점수
  min_duration: 15                 # 최소 클립 길이
  max_duration: 40                 # 최대 클립 길이

# 5단계: 클립 경계 조정 (VAD 기반)
clip_refiner:
  max_extend_seconds: 3.0           # 최대 확장 가능 길이 (초)
  silence_padding: 0.05             # 무음 구간 발견 시 추가 패딩 (초)
  extend_on_speech_boundary: true   # 음성 경계에 맞춰 확장 (true/false)

# 출력 설정
output:
  base_dir: "outputs/clip_analysis"
  save_details: true
  include_debug_info: false